		//页面加载完毕后加载js
		var onload2=function(){
			//图一
			var myChart=echarts.init(document.getElementById('container1'));
			var option = {
				title:{
				//	text:'2017年郑州AQI柱状图',
				//subtext:'http://www.pm2.5.in',//副标签
					//sublink:'http://www.pm2.5.in',//副标题链接
					//left:'center',
					textStyle:{
						color:'rgba(0,0,0,0.8)',
						fontSize:16,
						lineHeight:16
					},
					subtextStyle:{
						padding:0,//标题内边距
						//itemGap:100,//主副标题之间的距离
						fontSize:15,
						borderColor:'red'
					}
					},
					tooltip:{
					trigger:'axis'//坐标轴触发提示项
				},
				//图例组件
				//工具栏
					toolbox:{
					show:true,
					feature:{
						mark:{show:true},
						dataView:{show:true,readyOnly:false},//展现当前图表所用数据
						magicType:{show:true,type:['bar','line']},//动态类型切换
						restore:{show:true},//配置项还原
						saveAsImage:{show:true}					
					}
					},
					//直角坐标系在grid中的x轴
				xAxis:{
					data:["优","良","轻度污染","中度污染","重度污染","严重污染"]
				},
				//直角坐标系在grid中的y轴
				yAxis:{
					name:'AQI天数（天）'
				},
				//系列列表
				series:[{
					name:'AQI天数',
					type:'bar',
					data:[2,69,84,28,23,6],
					barMaxWidth :'30%',
					itemStyle:{
							normal:{
								color:function(params){
									var colorList=['#00E400','#FFFF00','#FF7E00','#FF0000',
								'#99004C','#4C0026']
									return colorList[params.dataIndex]
								}
								//color:'#c04346',//柱条颜色
								//shadowBlur:200,//图形阴影模糊大小
								//shadowOffsetX:0,//阴影水平方向上的偏移距离
							//	shadowOffsetY:0,
								//shadowColor:'rgba(0,0,0,0.5)'//阴影颜色
							},
							emphasis:{
								shadowBlur:200,
								shadowColor:'rgba(237,248,233,0.8)'
							}
						}
				}],
				//全局文本设置
				textStyle:{
					color:'rgba(0,0,0,0.6)'
				},
				//设置标签的视觉引导线颜色
			 labelLine:{
			 	normal:{
			 		lineStyle:{
			 			color:'rgba(255,255,255,0.3)'
			 		}
			 	}
			 }
		};
		 myChart.setOption(option);
		 //图二
		 var myChart=echarts.init(document.getElementById('container2'));
			var option = {
				title:{
					text:'PM2.5折线图'
				},
				tooltip:{
					trigger:'axis'//坐标轴触发提示项
				},
				legend:{
					data:['PM2.5']//图例名称
				},
				toolbox:{
					show:true,
					feature:{
						mark:{show:true},
						dataView:{show:true,readyOnly:false},//展现当前图表所用数据
						magicType:{show:true,type:['line','bar']},//动态类型切换
						restore:{show:true},//配置项还原
						saveAsImage:{show:true}					
					}
				},
				calculable:true,//是否显示拖拽用的手柄
				xAxis:{
					type:'category',//离散型数据
     //boundaryGap:false,
					data:["冬","春","夏","秋","冬","春","夏","秋","冬","春","夏","秋","冬","春","夏"]
				},
				yAxis:{},
				series:[{
					name:'PM2.5',
					type:'line',//折线图
					data:[184,153,123,155,212,175,128,143,209,171,82,125,201,150,96],
					itemStyle:{
						normal:{
							shadowBlur:200,
							shadowOffsetX:0,
							shadowOffsetY:0,
							shadowColor:'rgba(0,0,0,0.5)'
						},
							emphasis:{
							shadowBlur:200,
							shadowColor:'rgba(237,248,233,0.8)'
						}
					}
				}],
				//全局文本设置
	    textStyle:{
					color:'rgba(0,0,0,0.6)'
				},
				//设置标签的视觉引导线颜色
			 labelLine:{
			 	normal:{
			 		lineStyle:{
			 			color:'rgba(255,255,255,0.3)'
			 		}
			 	}
			 }
			};
			myChart.setOption(option);
			//图三
					 var myChart=echarts.init(document.getElementById('container3'));
			var option = {
				title:{
					text:'饼图',
					textStyle:{
						color:'rgba(0,0,0,0.8)',
						fontSize:16,
						lineHeight:16
					}
				},
//				tooltip:{
//					trigger:'axis'//坐标轴触发提示项
//				},
				legend:{
					orient:'vertical',//图例列表的布局朝向
					left:'left',
					data:['良','轻度污染','中度污染','重度污染','严重污染','优'],//图例名称
					padding:[30,0,0,20],
					textStyle:{
						color:'rgba(0,0,0,0.6)',
						fontSize:10
					}
				},
				toolbox:{
					show:true,
					feature:{
						mark:{show:true},
						dataView:{show:true,readyOnly:false},//展现当前图表所用数据
						magicType:{show:true,type:['pie','bar']},//动态类型切换
						restore:{show:true},//配置项还原
						saveAsImage:{show:true}					
					}
				},
				calculable:true,//是否显示拖拽用的手柄
				series:[{
					name:'AQI',
					type:'pie',//折线图
					clockwise:false,//逆时针旋转
					data:[
						{value:69,name:'良'},				
						{value:84,name:'轻度污染'},
						{value:28,name:'中度污染'},
						{value:23,name:'重度污染'},
						{value:6,name:'严重污染'},
						{value:2,name:'优'},						
					],
					color:['#FFFF00','#FF7E00','#FF0000',
								'#99004C','#4C0026','#00E400'],
					itemStyle:{
						normal:{
							//shadowBlur:200,
							//shadowOffsetX:0,
							//shadowOffsetY:0,
							//shadowColor:'rgba(0,0,0,0.5)'
						},
							emphasis:{
							shadowBlur:200,
							shadowColor:'rgba(237,248,233,0.8)'
						}
					}
				}],
	    textStyle:{
					color:'rgba(0,0,0,0.6)'
				},
				//设置标签的视觉引导线颜色
			 labelLine:{
			 	normal:{
			 		lineStyle:{
			 			color:'rgba(255,255,255,0.3)'
			 		}
			 	}
			 }
			};
			myChart.setOption(option);
		}

		